### ISSUE TITLE
BOM?

### ISSUE THREAD

**Issue by sixtyfive** [Chrismettal/EleLab_v2#7]
Hi, do you have a BOM with some sourcing info, for e.g. the stepdown converter modules you used, etc., available somewhere?

**Comment by Chrismettal** [comment]
Hey,

since almost all of the modules, especially the step-down converters come from china and never really come with any relatable product numbers it's really hard to pinpoint a linkable source. Most sources of the step-down converter i could give you won't be working in a few months. Stuff with actual product numbers, like a DSO138 oscilloscope i can link, but "Generic step-down that looks like this" is a difficult one to link.

I made sure to write such a note to every module that is not easy to link with good search terms and pictures. Sorry i can't give you better instructions than "look on eBay / Aliexpress for the terms i provide and check the pictures".

I also made sure to always use very abundant modules so they actually show up in the first few cheap offers from china on either site to circumvent that problem a bit.

**Comment by Chrismettal** [comment]
Small correction, i DID find the chip that was used on that specific step-down converter, which is a XL4016. This module seems to go by that name too. I will add that to the Readme.

All the other parts are pretty much the first result when you google the terms i provided.
