### ISSUE TITLE
Mirror on Github

### ISSUE THREAD

**Issue by r3vit** [Chrismettal/EleLab_v2#8]
@Chrismettal it's possible to add a mirror copy from Gitlab to Github?

[Here](https://docs.gitlab.com/ee/user/project/repository/repository_mirroring.html) there are the instruction from Gitlab (main on Gitlab -> mirror on Github). Just to not lose the good star/forks integration here and follow the changes from Github :)

If there is a reason to have this moved completely I'm ok with that, just... there is also this option.

Anyway thank you for this project, it's really inspiring 😄

**Comment by Chrismettal** [comment]
Hey, 

thanks for your suggestion. I will definitely keep this repo up especially because lots of sources link here now (and I like seeing the stars to be honest) but I want to encourage interaction specifically with the Gitlab repo instead of here. If people want to fork and open PRs, I would be very happy to accept them over at Gitlab. 

But you are right, if I keep the Github repo open anyways, I might as well make it a passive mirror to track the Gitlab changes. Might need to figure out if it is possible to keep the README not touched by the mirror so I can add a big warning to Github only, linking to the new location for potential contributions.

Thank you!

**Comment by Chrismettal** [comment]
![image](https://user-images.githubusercontent.com/39636046/125480924-b530ced1-c799-4e8e-adb7-e2fa14baf3ee.png)
